-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnvNzngm1C/5s4PnM
1OTNRCbbZw0gUmhjtRL4c4r8XYegCgYIKoZIzj0DAQehRANCAASd12HCqpBFjv+a
CAwcDYhMQAIez1fUtwfRRyCjObtHFjuVlur2EhCX+rytQnajG+iVkr8AudT8QA3k
wIPpb1G4
-----END PRIVATE KEY-----